### ISSUE TITLE
Using tge same secrets in multiple namespaces

### ISSUE THREAD

**Issue by adrian-gierakowski** [Soluto/kamus#190] opened 2019-05-12 17:59 UTC
Hi, firstly I'd like to thank you for the work you put into this project. It looks like it provides exactly the functionality I've been looking for. 

One thing however is not clear to me. If I wanted to use the same set of secret credentials in multiple namespaces, would I have to encrypt them separately for each namespace? 

Or is it possible to encrypt once and have the secrets decrypted by init containers running in different namespaces? 

For example, I've got staging Secrets which I usually access from an app running in the default namespace. Now I'd like to deploy a temporary copy of the app in a different namespace, using the staging credentials. Can I create a Secrets object identical to the one in the default namespace (avoiding having to reencrypt it's content) and have it decrypted by an init container in the temporary namespace? Thanks!

**Comment by omerlh** [comment] 2019-05-12 18:21
Hey @adrian-gierakowski! I'm happy to hear that, thank you for your kind words!
By design, no - Kamus let you encrypt a secret for a specific SA in a specific namespace. This is the basic layer of protection in Kamus - ensuring that one leaked SA token does not affect the entire system. There are a few ways to solve this issue the way you want:
 * Using the AES key encryption - which uses one key for all SA. In this (insecure) scenario the decryption will work as expected.
* Copy the SA token from the original SA (using kubectl get secret or something like that) and impersonate it in the init container. Hacky, but will work.

What do you think? Another option is to reconsider the flow. Kamus was designed to encrypt secrets for a specific SA. This is not something I'm willing to change...

**Comment by adrian-gierakowski** [comment] 2019-05-14 21:02
Thank you for your detailed answer. I need to ponder a little bit on this and will come back with some conclusions or further questions once I'm ready. Best wishes!

**Comment by omerlh** [comment] 2019-05-15 05:07
Thank you :) May I go ahead and close this issue in the meanwhile?

**Closed** 2019-05-17 06:30 UTC
Labels: question
